name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r showup-core/requirements.txt
          pip install -r showup-editor-ui/requirements.txt
          pip install -e ./showup-core
          pip install pytest
      - name: Run tests
        run: pytest -q
